import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Logo from '../Component/logo'
import SearchBar from '../Component/searchbar'
import Marketplace from '../Component/marketplace'
import Notification from '../Component/notification'
import Heading from '../Component/heading'
import Cards from '../Component/cards'
// import styled from '@emotion/styled'
import Footer from '../Component/footer'

// const content = styled.div`
//   padding: 4rem 0;
//   flex: 1;
//   display: flex;
//   flex-direction: row;
//   justify-content: space-around;
//   align-items: flex-start;
//   background-color: red;
// `;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.main}>
          <Logo/>
          <SearchBar/>
          <Marketplace/>
          <Notification/>
      </div>
          <Heading/>
          <Cards/>
          

      <footer className={styles.footer}>
          {/* <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a> */}
          <Footer/>
        </footer>
    </div>
  )
}
