import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Logo from '../Component/Logo'
import SearchBar from '../Component/Searchbar'
import Marketplace from '../Component/Marketplace'
import Heading from '../Component/Heading'
import Cards from '../Component/Cards'
import styled from '@emotion/styled'
import Footer from '../Component/Footer'

const Content = styled.div`
  padding: 1.5rem 0;
  flex: 1;
  display: flex;
  flex-direction: row;
  justify-content: space-evenly;
  align-items: flex-start;
  @media (max-width: 450px) {
      width: 200%;
      flex-direction: row;
  }
`;

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Next Assignment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Content>
          <Logo/>
          <SearchBar/>
          <Marketplace/>
      </Content>
          <Heading/>
          <Cards/>
          

      <footer className={styles.footer}>
          <Footer/>
        </footer>
    </div>
  )
}
